/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as LoyaltyProgramRouteImport } from './routes/loyalty-program'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as VerifiedRouteImport } from './routes/verified'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as BranchesIndexRouteImport } from './routes/branches.index'
import { Route as BranchesBranchIdRouteImport } from './routes/branches.$branchId'
import { Route as CampaignsIndexRouteImport } from './routes/campaigns.index'
import { Route as CampaignsCampaignIdRouteImport } from './routes/campaigns.$campaignId'
import { Route as CustomersIndexRouteImport } from './routes/customers.index'
import { Route as CustomersCustomerIdRouteImport } from './routes/customers.$customerId'
import { Route as JoinProgramIdRouteImport } from './routes/join.$programId'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding.index'
import { Route as OnboardingBusinessCategoryRouteImport } from './routes/onboarding.business-category'
import { Route as OnboardingBusinessTypeRouteImport } from './routes/onboarding.business-type'
import { Route as OnboardingPlanRouteImport } from './routes/onboarding.plan'
import { Route as OnboardingSuccessRouteImport } from './routes/onboarding.success'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const LoyaltyProgramRoute = LoyaltyProgramRouteImport.update({
  id: '/loyalty-program',
  path: '/loyalty-program',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifiedRoute = VerifiedRouteImport.update({
  id: '/verified',
  path: '/verified',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchesIndexRoute = BranchesIndexRouteImport.update({
  id: '/branches/',
  path: '/branches/',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchesBranchIdRoute = BranchesBranchIdRouteImport.update({
  id: '/branches/$branchId',
  path: '/branches/$branchId',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsIndexRoute = CampaignsIndexRouteImport.update({
  id: '/campaigns/',
  path: '/campaigns/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsCampaignIdRoute = CampaignsCampaignIdRouteImport.update({
  id: '/campaigns/$campaignId',
  path: '/campaigns/$campaignId',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIndexRoute = CustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersCustomerIdRoute = CustomersCustomerIdRouteImport.update({
  id: '/customers/$customerId',
  path: '/customers/$customerId',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinProgramIdRoute = JoinProgramIdRouteImport.update({
  id: '/join/$programId',
  path: '/join/$programId',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingBusinessCategoryRoute =
  OnboardingBusinessCategoryRouteImport.update({
    id: '/business-category',
    path: '/business-category',
    getParentRoute: () => OnboardingRoute,
  } as any)
const OnboardingBusinessTypeRoute = OnboardingBusinessTypeRouteImport.update({
  id: '/business-type',
  path: '/business-type',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingPlanRoute = OnboardingPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingSuccessRoute = OnboardingSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => OnboardingRoute,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analytics': typeof AnalyticsRoute
  '/change-password': typeof ChangePasswordRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/guide': typeof GuideRoute
  '/loyalty-program': typeof LoyaltyProgramRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/verified': typeof VerifiedRoute
  '/verify': typeof VerifyRoute
  '/branches/$branchId': typeof BranchesBranchIdRoute
  '/campaigns/$campaignId': typeof CampaignsCampaignIdRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/join/$programId': typeof JoinProgramIdRoute
  '/onboarding/business-category': typeof OnboardingBusinessCategoryRoute
  '/onboarding/business-type': typeof OnboardingBusinessTypeRoute
  '/onboarding/plan': typeof OnboardingPlanRoute
  '/onboarding/success': typeof OnboardingSuccessRoute
  '/branches/': typeof BranchesIndexRoute
  '/campaigns/': typeof CampaignsIndexRoute
  '/customers/': typeof CustomersIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analytics': typeof AnalyticsRoute
  '/change-password': typeof ChangePasswordRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/guide': typeof GuideRoute
  '/loyalty-program': typeof LoyaltyProgramRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/verified': typeof VerifiedRoute
  '/verify': typeof VerifyRoute
  '/branches/$branchId': typeof BranchesBranchIdRoute
  '/campaigns/$campaignId': typeof CampaignsCampaignIdRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/join/$programId': typeof JoinProgramIdRoute
  '/onboarding/business-category': typeof OnboardingBusinessCategoryRoute
  '/onboarding/business-type': typeof OnboardingBusinessTypeRoute
  '/onboarding/plan': typeof OnboardingPlanRoute
  '/onboarding/success': typeof OnboardingSuccessRoute
  '/branches': typeof BranchesIndexRoute
  '/campaigns': typeof CampaignsIndexRoute
  '/customers': typeof CustomersIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analytics': typeof AnalyticsRoute
  '/change-password': typeof ChangePasswordRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/guide': typeof GuideRoute
  '/loyalty-program': typeof LoyaltyProgramRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/verified': typeof VerifiedRoute
  '/verify': typeof VerifyRoute
  '/branches/$branchId': typeof BranchesBranchIdRoute
  '/campaigns/$campaignId': typeof CampaignsCampaignIdRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/join/$programId': typeof JoinProgramIdRoute
  '/onboarding/business-category': typeof OnboardingBusinessCategoryRoute
  '/onboarding/business-type': typeof OnboardingBusinessTypeRoute
  '/onboarding/plan': typeof OnboardingPlanRoute
  '/onboarding/success': typeof OnboardingSuccessRoute
  '/branches/': typeof BranchesIndexRoute
  '/campaigns/': typeof CampaignsIndexRoute
  '/customers/': typeof CustomersIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/analytics'
    | '/change-password'
    | '/contact'
    | '/dashboard'
    | '/features'
    | '/forgot-password'
    | '/guide'
    | '/loyalty-program'
    | '/onboarding'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/settings'
    | '/signin'
    | '/signup'
    | '/terms'
    | '/verified'
    | '/verify'
    | '/branches/$branchId'
    | '/campaigns/$campaignId'
    | '/customers/$customerId'
    | '/join/$programId'
    | '/onboarding/business-category'
    | '/onboarding/business-type'
    | '/onboarding/plan'
    | '/onboarding/success'
    | '/branches/'
    | '/campaigns/'
    | '/customers/'
    | '/onboarding/'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/analytics'
    | '/change-password'
    | '/contact'
    | '/dashboard'
    | '/features'
    | '/forgot-password'
    | '/guide'
    | '/loyalty-program'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/settings'
    | '/signin'
    | '/signup'
    | '/terms'
    | '/verified'
    | '/verify'
    | '/branches/$branchId'
    | '/campaigns/$campaignId'
    | '/customers/$customerId'
    | '/join/$programId'
    | '/onboarding/business-category'
    | '/onboarding/business-type'
    | '/onboarding/plan'
    | '/onboarding/success'
    | '/branches'
    | '/campaigns'
    | '/customers'
    | '/onboarding'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/analytics'
    | '/change-password'
    | '/contact'
    | '/dashboard'
    | '/features'
    | '/forgot-password'
    | '/guide'
    | '/loyalty-program'
    | '/onboarding'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/settings'
    | '/signin'
    | '/signup'
    | '/terms'
    | '/verified'
    | '/verify'
    | '/branches/$branchId'
    | '/campaigns/$campaignId'
    | '/customers/$customerId'
    | '/join/$programId'
    | '/onboarding/business-category'
    | '/onboarding/business-type'
    | '/onboarding/plan'
    | '/onboarding/success'
    | '/branches/'
    | '/campaigns/'
    | '/customers/'
    | '/onboarding/'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AnalyticsRoute: typeof AnalyticsRoute
  ChangePasswordRoute: typeof ChangePasswordRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  FeaturesRoute: typeof FeaturesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GuideRoute: typeof GuideRoute
  LoyaltyProgramRoute: typeof LoyaltyProgramRoute
  OnboardingRoute: typeof OnboardingRouteWithChildren
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  VerifiedRoute: typeof VerifiedRoute
  VerifyRoute: typeof VerifyRoute
  BranchesBranchIdRoute: typeof BranchesBranchIdRoute
  CampaignsCampaignIdRoute: typeof CampaignsCampaignIdRoute
  CustomersCustomerIdRoute: typeof CustomersCustomerIdRoute
  JoinProgramIdRoute: typeof JoinProgramIdRoute
  BranchesIndexRoute: typeof BranchesIndexRoute
  CampaignsIndexRoute: typeof CampaignsIndexRoute
  CustomersIndexRoute: typeof CustomersIndexRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loyalty-program': {
      id: '/loyalty-program'
      path: '/loyalty-program'
      fullPath: '/loyalty-program'
      preLoaderRoute: typeof LoyaltyProgramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verified': {
      id: '/verified'
      path: '/verified'
      fullPath: '/verified'
      preLoaderRoute: typeof VerifiedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branches/': {
      id: '/branches/'
      path: '/branches'
      fullPath: '/branches/'
      preLoaderRoute: typeof BranchesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branches/$branchId': {
      id: '/branches/$branchId'
      path: '/branches/$branchId'
      fullPath: '/branches/$branchId'
      preLoaderRoute: typeof BranchesBranchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/': {
      id: '/campaigns/'
      path: '/campaigns'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof CampaignsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$campaignId': {
      id: '/campaigns/$campaignId'
      path: '/campaigns/$campaignId'
      fullPath: '/campaigns/$campaignId'
      preLoaderRoute: typeof CampaignsCampaignIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/': {
      id: '/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof CustomersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/$customerId': {
      id: '/customers/$customerId'
      path: '/customers/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof CustomersCustomerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$programId': {
      id: '/join/$programId'
      path: '/join/$programId'
      fullPath: '/join/$programId'
      preLoaderRoute: typeof JoinProgramIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/business-category': {
      id: '/onboarding/business-category'
      path: '/business-category'
      fullPath: '/onboarding/business-category'
      preLoaderRoute: typeof OnboardingBusinessCategoryRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/business-type': {
      id: '/onboarding/business-type'
      path: '/business-type'
      fullPath: '/onboarding/business-type'
      preLoaderRoute: typeof OnboardingBusinessTypeRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/plan': {
      id: '/onboarding/plan'
      path: '/plan'
      fullPath: '/onboarding/plan'
      preLoaderRoute: typeof OnboardingPlanRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/success': {
      id: '/onboarding/success'
      path: '/success'
      fullPath: '/onboarding/success'
      preLoaderRoute: typeof OnboardingSuccessRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface OnboardingRouteChildren {
  OnboardingBusinessCategoryRoute: typeof OnboardingBusinessCategoryRoute
  OnboardingBusinessTypeRoute: typeof OnboardingBusinessTypeRoute
  OnboardingPlanRoute: typeof OnboardingPlanRoute
  OnboardingSuccessRoute: typeof OnboardingSuccessRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingBusinessCategoryRoute: OnboardingBusinessCategoryRoute,
  OnboardingBusinessTypeRoute: OnboardingBusinessTypeRoute,
  OnboardingPlanRoute: OnboardingPlanRoute,
  OnboardingSuccessRoute: OnboardingSuccessRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AnalyticsRoute: AnalyticsRoute,
  ChangePasswordRoute: ChangePasswordRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  FeaturesRoute: FeaturesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GuideRoute: GuideRoute,
  LoyaltyProgramRoute: LoyaltyProgramRoute,
  OnboardingRoute: OnboardingRouteWithChildren,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  VerifiedRoute: VerifiedRoute,
  VerifyRoute: VerifyRoute,
  BranchesBranchIdRoute: BranchesBranchIdRoute,
  CampaignsCampaignIdRoute: CampaignsCampaignIdRoute,
  CustomersCustomerIdRoute: CustomersCustomerIdRoute,
  JoinProgramIdRoute: JoinProgramIdRoute,
  BranchesIndexRoute: BranchesIndexRoute,
  CampaignsIndexRoute: CampaignsIndexRoute,
  CustomersIndexRoute: CustomersIndexRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
